-- MySQL Script generated by MySQL Workbench
-- Sun Apr 16 02:04:32 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dbproject
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbproject
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbproject` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `dbproject` ;

-- -----------------------------------------------------
-- Table `dbproject`.`activity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbproject`.`activity` (
  `aid` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `start_date` DATE NULL DEFAULT NULL,
  `duration` SMALLINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`aid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbproject`.`faculty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbproject`.`faculty` (
  `fid` CHAR(2) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `name_th` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `name_en` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  PRIMARY KEY (`fid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbproject`.`department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbproject`.`department` (
  `did` INT(11) NOT NULL AUTO_INCREMENT,
  `name_th` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `name_en` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `fid` CHAR(2) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  PRIMARY KEY (`did`),
  INDEX `fk_department_faculty_idx` (`fid` ASC),
  CONSTRAINT `fk_department_faculty`
    FOREIGN KEY (`fid`)
    REFERENCES `dbproject`.`faculty` (`fid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbproject`.`major`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbproject`.`major` (
  `mid` INT(11) NOT NULL AUTO_INCREMENT,
  `name_en` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `name_th` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `did` INT(11) NOT NULL,
  `required_lang` INT(3) NOT NULL,
  `required_approve` INT(3) NOT NULL,
  PRIMARY KEY (`mid`),
  INDEX `fk_major_department_idx` (`did` ASC),
  CONSTRAINT `fk_major_department`
    FOREIGN KEY (`did`)
    REFERENCES `dbproject`.`department` (`did`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbproject`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbproject`.`student` (
  `sid` CHAR(10) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `fname_th` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `fname_en` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `lname_th` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `lname_en` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `initial_name` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `address_en` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `address_th` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `ent_year` SMALLINT(4) NOT NULL,
  `behav_score` SMALLINT(3) NOT NULL,
  `mid` INT(11) NOT NULL,
  PRIMARY KEY (`sid`),
  INDEX `fk_student_major_idx` (`mid` ASC),
  CONSTRAINT `fk_student_major`
    FOREIGN KEY (`mid`)
    REFERENCES `dbproject`.`major` (`mid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbproject`.`student_activity_awarded`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbproject`.`student_activity_awarded` (
  `sid` CHAR(10) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `aid` INT(11) NOT NULL,
  `award` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`sid`, `aid`),
  INDEX `fk_student_activity_awarded_student_idx` (`sid` ASC),
  INDEX `fk_student_activity_awarded_activity_idx` (`aid` ASC),
  CONSTRAINT `fk_student_activity_awarded_activity`
    FOREIGN KEY (`aid`)
    REFERENCES `dbproject`.`activity` (`aid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_activity_awarded_student`
    FOREIGN KEY (`sid`)
    REFERENCES `dbproject`.`student` (`sid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbproject`.`student_activity_join`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbproject`.`student_activity_join` (
  `sid` CHAR(10) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `aid` INT(11) NOT NULL,
  PRIMARY KEY (`sid`, `aid`),
  INDEX `fk_student_activity_join_activity_idx` (`aid` ASC),
  INDEX `fk_student_activity_join_student_idx` (`sid` ASC),
  CONSTRAINT `fk_student_activity_join_activity`
    FOREIGN KEY (`aid`)
    REFERENCES `dbproject`.`activity` (`aid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_activity_join_student`
    FOREIGN KEY (`sid`)
    REFERENCES `dbproject`.`student` (`sid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbproject`.`absent_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbproject`.`absent_record` (
  `arid` INT NOT NULL AUTO_INCREMENT,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`arid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbproject`.`absent_record_has_student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbproject`.`absent_record_has_student` (
  `arid` INT NOT NULL,
  `sid` CHAR(10) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  PRIMARY KEY (`arid`, `sid`),
  INDEX `fk_absent_record_has_student_student_idx` (`sid` ASC),
  INDEX `fk_absent_record_has_student_absent_record_idx` (`arid` ASC),
  CONSTRAINT `fk_absent_record_has_student_absent_record`
    FOREIGN KEY (`arid`)
    REFERENCES `dbproject`.`absent_record` (`arid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_absent_record_has_student_student`
    FOREIGN KEY (`sid`)
    REFERENCES `dbproject`.`student` (`sid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbproject`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbproject`.`course` (
  `course_no` CHAR(7) NOT NULL,
  `name_en` VARCHAR(100) NOT NULL,
  `name_th` VARCHAR(100) NOT NULL,
  `shortname` VARCHAR(50) NULL DEFAULT NULL,
  `credit` SMALLINT(2) NULL DEFAULT NULL,
  `subcredit_1` SMALLINT(2) NULL DEFAULT NULL,
  `subcredit_2` SMALLINT(2) NULL DEFAULT NULL,
  `subcredit_3` SMALLINT(2) NULL DEFAULT NULL,
  `course_detail` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `special_type` ENUM('0', '1', '2', '3', '4', '5', '6') NULL DEFAULT NULL,
  `did` INT NOT NULL,
  PRIMARY KEY (`course_no`),
  INDEX `fk_course_department_idx` (`did` ASC),
  CONSTRAINT `fk_course_department`
    FOREIGN KEY (`did`)
    REFERENCES `dbproject`.`department` (`did`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbproject`.`course_prerequisite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbproject`.`course_prerequisite` (
  `course_no` CHAR(7) NOT NULL,
  `pre_course_no` CHAR(7) NOT NULL,
  PRIMARY KEY (`pre_course_no`, `course_no`),
  INDEX `fk_course_prerequisite_course_course_idx` (`course_no` ASC),
  INDEX `fk_course_prerequisite_course_pre_course_idx` (`pre_course_no` ASC),
  CONSTRAINT `fk_course_prerequisite_course_course`
    FOREIGN KEY (`course_no`)
    REFERENCES `dbproject`.`course` (`course_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_course_prerequisite_course_pre_course`
    FOREIGN KEY (`pre_course_no`)
    REFERENCES `dbproject`.`course` (`course_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbproject`.`major_course_required`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbproject`.`major_course_required` (
  `mid` INT(11) NOT NULL,
  `course_no` CHAR(7) NOT NULL,
  PRIMARY KEY (`mid`, `course_no`),
  INDEX `fk_major_course_required_major_idx` (`mid` ASC),
  INDEX `fk_major_course_required_course_idx` (`course_no` ASC),
  CONSTRAINT `fk_major_course_required_major`
    FOREIGN KEY (`mid`)
    REFERENCES `dbproject`.`major` (`mid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_major_course_required_course`
    FOREIGN KEY (`course_no`)
    REFERENCES `dbproject`.`course` (`course_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbproject`.`student_semester_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbproject`.`student_semester_info` (
  `sid` CHAR(10) NOT NULL,
  `semester` TINYINT(1) NOT NULL,
  `year` YEAR NOT NULL,
  PRIMARY KEY (`sid`, `year`, `semester`),
  CONSTRAINT `fk_student_semester_info_student`
    FOREIGN KEY (`sid`)
    REFERENCES `dbproject`.`student` (`sid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbproject`.`enrollment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbproject`.`enrollment` (
  `eid` INT NOT NULL AUTO_INCREMENT,
  `created_time` DATETIME NULL DEFAULT NULL,
  `grade` VARCHAR(2) NULL DEFAULT NULL,
  `edited_time` DATETIME NULL DEFAULT NULL,
  `course_no` CHAR(7) NOT NULL,
  `sid` CHAR(10) NOT NULL,
  `semester` TINYINT(1) NOT NULL,
  `year` YEAR NOT NULL,
  PRIMARY KEY (`eid`),
  INDEX `fk_enrollment_course_idx` (`course_no` ASC),
  INDEX `fk_enrollment_student_semester_info_idx` (`sid` ASC, `semester` ASC, `year` ASC),
  CONSTRAINT `fk_enrollment_course`
    FOREIGN KEY (`course_no`)
    REFERENCES `dbproject`.`course` (`course_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_enrollment_student_semester_info`
    FOREIGN KEY (`sid` , `year`, `semester`)
    REFERENCES `dbproject`.`student_semester_info` (`sid`, `year`, `semester`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbproject`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbproject`.`user` (
  `id` VARCHAR(30) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `display_name` VARCHAR(200) NOT NULL,
  `type` ENUM('A', 'M') NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbproject`.`user_student_advice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbproject`.`user_student_advice` (
  `user_id` VARCHAR(30) NOT NULL,
  `student_sid` CHAR(10) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  PRIMARY KEY (`user_id`, `student_sid`),
  INDEX `fk_user_student_advice_student_idx` (`student_sid` ASC),
  INDEX `fk_user_student_advice_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_student_advice_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `dbproject`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_student_advice_student`
    FOREIGN KEY (`student_sid`)
    REFERENCES `dbproject`.`student` (`sid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
